name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit_testing:
    name: Unit Testing
    strategy:
      matrix:
        node-version: [24,23]
        os: [ubuntu-latest, windows-latest]
        exclude:
        - node-version: 24
          os: windows-latest
        include:
        - node-version: 22
          os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: test-results.xml