name: Solar System Workflow
on:
    push:
        branches:
            - main
            - feature/**
    workflow_dispatch:

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        name: unit-testing
        steps:
            - name: clone the repo 
              uses: actions/checkout@v4 
            
            - name: Nodejs setup
              uses: actions/setup-node@v4
              with:
                node-version: 24 
            
            - name: Install Dependencies 
              run: npm install

            - name: Run Unit Tests 
              run: npm test

            - name: Archive Test Results 
              uses: actions/upload-artifact@v4 
              with: 
                name: mocha-test-result 
                path: test-results.xml
    
    Code-Coverage:
        runs-on: ubuntu-latest
        name: Code-Coverage
        steps:
            - name: clone the repo 
              uses: actions/checkout@v4 
            
            - name: Nodejs setup
              uses: actions/setup-node@v4
              with:
                node-version: 24 
            
            - name: Install Dependencies 
              run: npm install

            - name: Check Code Coverage
              run: npm run coverage
            
            - name: Archive Test Results 
              uses: actions/upload-artifact@v4 
              with: 
                name: code-coverage
                path: coverage
                retention-days: 5



